### PR TITLE
Adds Dot, removes Sel

### PR DESCRIPTION
**Pull request by davelondon**

### CODE REVIEW

**Comment by davelondon** [comment]
This is a better fix for https://github.com/davelondon/jennifer/issues/6

**Comment by davelondon** [comment]
@nicolai86 what do you think about this?

**Comment by davelondon** [comment]
With this change:

```go
Sel(Id("foo"), Id("bar"), Id("baz"))
```

... would become:

```go
Id("foo").Dot("bar").Dot("baz")
```

... I think it reads much nicer...

**Comment by nicolai86** [comment]
@davelondon is there still a way to do variadic concatenation as `Sel` did?

**Comment by davelondon** [comment]
I really never liked Sel... Hopefully there's no need for it now... I don't think a chain of selectors realistically ever needs to be treated as a list...

**Comment by nicolai86** [comment]
I'm using it a lot but not for variadic statements. Will play with jen based off this pr tonight and let you know how it goes :)

**Comment by davelondon** [comment]
... I don't think anything apart from an identifier ever comes after a period in Go (apart from a type assertion, which we support with `Assert`. So I don't think we need a more generic `func Dot(c Code)`.

**Comment by davelondon** [comment]
Hey I'm pretty happy with this, so I'm going to merge now... Let me know if you find any problems.

**Pull request merged**
