### PR TITLE
spelling nit: comprahensive

### PR DESCRIPTION
**Pull request by zellyn**

### CODE REVIEW

**Comment by davelondon** [comment]
Thanks, my spelling is atrocious.

**Comment by zellyn** [comment]
No problem. Github makes these kinds of corrections trivial now :-)

**Comment by davelondon** [comment]
Are you using jennifer on anything interesting? Feel free to open issues if you have any questions at all. I'm happy to help!

**Comment by zellyn** [comment]
No, but rebecca got mentioned in http://golangweekly.com/issues/149, so I was checking it out :-)

You should chat with the GoGoProtobuf guy and see what he's using for generating code… he might be interested. I'm slightly tempted to build a protobuf replacement that uses actual proper codegen.

**Pull request merged**
